
package eamcet;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Rahul
 */
public class LoginWindow extends javax.swing.JFrame {

    /**
     * Creates new form LoginWindow
     */
    public LoginWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminOrStudent = new javax.swing.ButtonGroup();
        logoPanel = new javax.swing.JPanel();
        eamcetLogo = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        adminRadio = new javax.swing.JRadioButton();
        studentRadio = new javax.swing.JRadioButton();
        adminStudentPanel = new javax.swing.JPanel();
        adminLayer = new javax.swing.JLayeredPane();
        emailLabel = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        adminLoginButton = new javax.swing.JButton();
        studentLayer = new javax.swing.JLayeredPane();
        mobileNumberLabel = new javax.swing.JLabel();
        mobileNumberField = new javax.swing.JTextField();
        studentPasswordLabel = new javax.swing.JLabel();
        studentPasswordField = new javax.swing.JPasswordField();
        studentLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(new java.awt.Dimension(2147483647, 2147483647));

        logoPanel.setBackground(new java.awt.Color(255, 255, 255));

        eamcetLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snistLogo.jpg"))); // NOI18N

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, logoPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(eamcetLogo)
                .addGap(38, 38, 38))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(eamcetLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loginPanel.setBackground(new java.awt.Color(204, 255, 255));

        adminRadio.setBackground(new java.awt.Color(204, 255, 255));
        adminOrStudent.add(adminRadio);
        adminRadio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        adminRadio.setSelected(true);
        adminRadio.setText("Admin");
        adminRadio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 153), 4, true));
        adminRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                adminRadioItemStateChanged(evt);
            }
        });
        adminRadio.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                adminRadioStateChanged(evt);
            }
        });
        adminRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminRadioActionPerformed(evt);
            }
        });

        studentRadio.setBackground(new java.awt.Color(204, 255, 255));
        adminOrStudent.add(studentRadio);
        studentRadio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        studentRadio.setText("student");
        studentRadio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentRadioItemStateChanged(evt);
            }
        });
        studentRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentRadioActionPerformed(evt);
            }
        });

        adminStudentPanel.setBackground(new java.awt.Color(204, 255, 255));
        adminStudentPanel.setLayout(new java.awt.CardLayout());

        adminLayer.setBackground(new java.awt.Color(255, 255, 255));
        adminLayer.setForeground(new java.awt.Color(255, 255, 255));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        emailLabel.setText("Email");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        emailField.setToolTipText("");
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passwordLabel.setText("Password");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        adminLoginButton.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        adminLoginButton.setText("Login");
        adminLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginButtonActionPerformed(evt);
            }
        });

        adminLayer.setLayer(emailLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminLayer.setLayer(emailField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminLayer.setLayer(passwordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminLayer.setLayer(passwordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        adminLayer.setLayer(adminLoginButton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout adminLayerLayout = new javax.swing.GroupLayout(adminLayer);
        adminLayer.setLayout(adminLayerLayout);
        adminLayerLayout.setHorizontalGroup(
            adminLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(adminLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminLayerLayout.createSequentialGroup()
                        .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminLayerLayout.createSequentialGroup()
                        .addComponent(passwordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                        .addGap(129, 129, 129))
                    .addComponent(passwordField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(adminLayerLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(adminLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        adminLayerLayout.setVerticalGroup(
            adminLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(adminLoginButton)
                .addContainerGap(32305, Short.MAX_VALUE))
        );

        adminStudentPanel.add(adminLayer, "card2");

        studentLayer.setBackground(new java.awt.Color(255, 255, 255));
        studentLayer.setForeground(new java.awt.Color(0, 0, 0));

        mobileNumberLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        mobileNumberLabel.setLabelFor(mobileNumberField);
        mobileNumberLabel.setText("Mobile Number");

        studentPasswordLabel.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        studentPasswordLabel.setLabelFor(studentPasswordField);
        studentPasswordLabel.setText("Password");

        studentLogin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        studentLogin.setText("Login");
        studentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentLoginActionPerformed(evt);
            }
        });

        studentLayer.setLayer(mobileNumberLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentLayer.setLayer(mobileNumberField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentLayer.setLayer(studentPasswordLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentLayer.setLayer(studentPasswordField, javax.swing.JLayeredPane.DEFAULT_LAYER);
        studentLayer.setLayer(studentLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout studentLayerLayout = new javax.swing.GroupLayout(studentLayer);
        studentLayer.setLayout(studentLayerLayout);
        studentLayerLayout.setHorizontalGroup(
            studentLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLayerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(studentLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentLayerLayout.createSequentialGroup()
                        .addComponent(studentPasswordLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69))
                    .addComponent(mobileNumberField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, studentLayerLayout.createSequentialGroup()
                        .addComponent(mobileNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(86, 86, 86)))
                .addContainerGap(881, Short.MAX_VALUE))
            .addGroup(studentLayerLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(studentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentLayerLayout.setVerticalGroup(
            studentLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentLayerLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(mobileNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mobileNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentPasswordLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentLogin)
                .addContainerGap())
        );

        adminStudentPanel.add(studentLayer, "card3");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(adminRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81)
                .addComponent(studentRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(135, 135, 135))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(adminStudentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(adminStudentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(logoPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(loginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void adminLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginButtonActionPerformed
        // TODO add your handling code here:
        String emailData,passwordData;
         emailData = emailField.getText().replaceAll("\\s","");
         passwordData = passwordField.getText().replaceAll("\\s","");
         if(emailData.isEmpty() || passwordData.isEmpty()){
             JOptionPane.showMessageDialog(null,"Please enter all details","blank",JOptionPane.INFORMATION_MESSAGE);
         }
         else{
         Connection con;
		PreparedStatement preparedStatement;
		try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
		con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rahul");
                System.out.print("hello)" +con);
//                        con = GetDBConnection.createConnection();
		ResultSet set  = null;
                String query = "select email,password from admindetails where email=? and password = ?";
                preparedStatement = con.prepareStatement(query);

           
            preparedStatement.setString(1,emailData);
            preparedStatement.setString(2, passwordData);
            set = preparedStatement.executeQuery();

              
            if(set.next()){
            
            this.dispose();  
             new Loading();
            
            JOptionPane.showMessageDialog(null,"Login Successful\nClick ok to continue");
            SetGetAdmin sga = new SetGetAdmin();
            sga.setEmail(emailData);
            sga.setPassword(passwordData);
            new AdminDetailsForAdminWindow(sga);
  
                }
                else
                   JOptionPane.showMessageDialog(null,"Admin details not found","Login Failed",JOptionPane.INFORMATION_MESSAGE);
                    
                }
		
		catch(SQLException sql) {
			sql.printStackTrace();
		}
                catch (ClassNotFoundException ex) {
                    Logger.getLogger(AdminWindow.class.getName()).log(Level.SEVERE, null, ex);
                }
         }
    }//GEN-LAST:event_adminLoginButtonActionPerformed

    private void adminRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminRadioActionPerformed
       

    }//GEN-LAST:event_adminRadioActionPerformed

    private void studentRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentRadioActionPerformed
        // TODO add your handling code here:
//         adminStudentPanel.removeAll();
//           adminStudentPanel.add(studentLayer);
//           adminStudentPanel.repaint();
//           adminStudentPanel.revalidate();
    }//GEN-LAST:event_studentRadioActionPerformed

    private void adminRadioStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_adminRadioStateChanged
        // TODO add your handling code here:
//            adminStudentPanel.removeAll();
//           adminStudentPanel.add(adminLayer);
//           adminStudentPanel.repaint();
//           adminStudentPanel.revalidate();
//        

    }//GEN-LAST:event_adminRadioStateChanged

    private void adminRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_adminRadioItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED){
            adminStudentPanel.removeAll();
           adminStudentPanel.add(adminLayer);
           adminStudentPanel.repaint();
           adminStudentPanel.revalidate();  
       
           
        }
     
        
    }//GEN-LAST:event_adminRadioItemStateChanged

    private void studentRadioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentRadioItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED)
        {
            adminStudentPanel.removeAll();
           adminStudentPanel.add(studentLayer);
           adminStudentPanel.repaint();
           adminStudentPanel.revalidate();
        
      
        }
    
    }//GEN-LAST:event_studentRadioItemStateChanged

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void studentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentLoginActionPerformed
         String studentMobileNumber;
         String studentPasswordData;
        studentMobileNumber= mobileNumberField.getText();
         studentPasswordData= new String(studentPasswordField.getPassword());
         Connection con;
		PreparedStatement preparedStatement;
		try {
		Class.forName("oracle.jdbc.driver.OracleDriver");
		System.out.println("Successfully connected");
		con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","system","rahul");
		ResultSet set  = null;
                String query = "select mobilenumber,password from studentdetails where mobilenumber=? and password = ?";
  
             preparedStatement = con.prepareStatement(query);

           
            preparedStatement.setString(1,studentMobileNumber);
            preparedStatement.setString(2, studentPasswordData);
            set = preparedStatement.executeQuery();

              
                if(set.next()){
                    JOptionPane.showMessageDialog(null, "Login Successful");
                    this.dispose();
                    new StudentWindow(studentMobileNumber,studentPasswordData);
                }
                else{
                    JOptionPane.showMessageDialog(null, "student Details not found");
                     
                
                }
                }
		catch(ClassNotFoundException cnf) {
			cnf.printStackTrace();
		}
		catch(SQLException sql) {
			sql.printStackTrace();
		}
                catch(NumberFormatException number ){
                    JOptionPane.showMessageDialog(null, "Please enter correct number");
                }
    }//GEN-LAST:event_studentLoginActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    
   
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginWindow().setVisible(true);
            }
        });
    }
    
  
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane adminLayer;
    private javax.swing.JButton adminLoginButton;
    private javax.swing.ButtonGroup adminOrStudent;
    private javax.swing.JRadioButton adminRadio;
    private javax.swing.JPanel adminStudentPanel;
    private javax.swing.JLabel eamcetLogo;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JTextField mobileNumberField;
    private javax.swing.JLabel mobileNumberLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLayeredPane studentLayer;
    private javax.swing.JButton studentLogin;
    private javax.swing.JPasswordField studentPasswordField;
    private javax.swing.JLabel studentPasswordLabel;
    private javax.swing.JRadioButton studentRadio;
    // End of variables declaration//GEN-END:variables
}
