/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package eamcet;

import java.awt.CardLayout;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;

/**
 *
 * @author Rahul
 */
public class Payment extends javax.swing.JPanel {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qualifyExam = new javax.swing.ButtonGroup();
        categoryPayment = new javax.swing.ButtonGroup();
        ph = new javax.swing.ButtonGroup();
        streamAppliedFor = new javax.swing.ButtonGroup();
        home1scroll = new javax.swing.JScrollPane();
        stepsToPayment = new javax.swing.JLayeredPane();
        heading = new javax.swing.JLabel();
        intermediateBranch = new javax.swing.JLabel();
        boardName = new javax.swing.JLabel();
        studentName = new javax.swing.JLabel();
        studentNumber = new javax.swing.JLabel();
        dateOfBirth = new javax.swing.JLabel();
        altNumber = new javax.swing.JLabel();
        secondYearHallTicket = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        category = new javax.swing.JLabel();
        physicallyHandicapped = new javax.swing.JLabel();
        certificateNumber = new javax.swing.JLabel();
        streamApplied = new javax.swing.JLabel();
        paymentMethod = new javax.swing.JLabel();
        bpc = new javax.swing.JRadioButton();
        mpc = new javax.swing.JRadioButton();
        diploma = new javax.swing.JRadioButton();
        mbpc = new javax.swing.JRadioButton();
        boardNameField = new javax.swing.JComboBox<>();
        secondYearHallticketField = new javax.swing.JTextField();
        studentNameField = new javax.swing.JTextField();
        dateOfBirthField = new javax.swing.JTextField();
        mobileNumberField = new javax.swing.JTextField();
        altNumberField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        oc = new javax.swing.JRadioButton();
        bcb = new javax.swing.JRadioButton();
        bcc = new javax.swing.JRadioButton();
        bca = new javax.swing.JRadioButton();
        bce = new javax.swing.JRadioButton();
        bcd = new javax.swing.JRadioButton();
        sc = new javax.swing.JRadioButton();
        st = new javax.swing.JRadioButton();
        phYes = new javax.swing.JRadioButton();
        phNo = new javax.swing.JRadioButton();
        certificate = new javax.swing.JTextField();
        agriMedical = new javax.swing.JRadioButton();
        engineering = new javax.swing.JRadioButton();
        bothEngAgri = new javax.swing.JRadioButton();
        payFee = new javax.swing.JButton();
        upi = new javax.swing.JRadioButton();
        password = new javax.swing.JLabel();
        studentPasswordField = new javax.swing.JPasswordField();
        back = new javax.swing.JButton();
        home2scroll = new javax.swing.JScrollPane();
        home2 = new javax.swing.JPanel();
        payingFeeLayer1 = new javax.swing.JLayeredPane();
        referenceNumberLabel1 = new javax.swing.JLabel();
        upiIdField1 = new javax.swing.JTextField();
        upiIfLabel1 = new javax.swing.JLabel();
        referenceNumberField1 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        home1scroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        stepsToPayment.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                stepsToPaymentMouseWheelMoved(evt);
            }
        });
        stepsToPayment.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        heading.setBackground(new java.awt.Color(255, 102, 102));
        heading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        heading.setText("FEE PAYMENT FOR SNIST-ENTRANCE 2024");
        stepsToPayment.add(heading, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 30, 1085, -1));

        intermediateBranch.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        intermediateBranch.setText("Group Subjects at Qualifying Examination* :");
        intermediateBranch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(intermediateBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 428, 24));

        boardName.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        boardName.setText("Name of the Board *: ");
        boardName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(boardName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 113, 464, 24));

        studentName.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        studentName.setText("Candidate's Name *: ");
        studentName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(studentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 208, 478, 24));

        studentNumber.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        studentNumber.setText("Candicates's / Student's Mobile Number *  :  ");
        studentNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(studentNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 275, -1, 24));

        dateOfBirth.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        dateOfBirth.setText("Date Of Birth*(as per SSC or Equivalent) :");
        dateOfBirth.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 245, 469, 24));

        altNumber.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        altNumber.setText("Alternate Mobile Number :");
        altNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(altNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 311, 284, 24));

        secondYearHallTicket.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        secondYearHallTicket.setText("Qualifying Exam Latest 2nd Year Hall Ticket Number *:  ");
        secondYearHallTicket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(secondYearHallTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, 478, 24));

        email.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        email.setText("E-Mail ID *(Personal) :");
        email.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 347, 263, 24));

        category.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        category.setText("Category * : ");
        category.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(category, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 377, 354, 24));

        physicallyHandicapped.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        physicallyHandicapped.setText("Physically Challenged (PH) * :");
        physicallyHandicapped.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(physicallyHandicapped, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 413, 319, 24));

        certificateNumber.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        certificateNumber.setText("If yes give SADARAM certificate Number :");
        certificateNumber.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(certificateNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 451, 487, 24));

        streamApplied.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        streamApplied.setText("Stream Applied For * :");
        streamApplied.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(streamApplied, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 487, 421, 24));

        paymentMethod.setFont(new java.awt.Font("Segoe UI Emoji", 2, 18)); // NOI18N
        paymentMethod.setText("Payment Type * :");
        paymentMethod.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stepsToPayment.add(paymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 589, 458, 24));

        qualifyExam.add(bpc);
        bpc.setText("BPC");
        bpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpcActionPerformed(evt);
            }
        });
        stepsToPayment.add(bpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(661, 84, 98, -1));

        qualifyExam.add(mpc);
        mpc.setText("MPC");
        mpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpcActionPerformed(evt);
            }
        });
        stepsToPayment.add(mpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 84, 98, -1));

        qualifyExam.add(diploma);
        diploma.setText("DIPLOMA");
        diploma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diplomaActionPerformed(evt);
            }
        });
        stepsToPayment.add(diploma, new org.netbeans.lib.awtextra.AbsoluteConstraints(765, 84, 98, -1));

        qualifyExam.add(mbpc);
        mbpc.setText("MBPC");
        stepsToPayment.add(mbpc, new org.netbeans.lib.awtextra.AbsoluteConstraints(869, 84, 98, -1));

        boardNameField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSC", "CBSE" }));
        boardNameField.setSelectedItem(null);
        boardNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardNameFieldActionPerformed(evt);
            }
        });
        stepsToPayment.add(boardNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 137, -1, -1));
        stepsToPayment.add(secondYearHallticketField, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 171, 72, 24));
        stepsToPayment.add(studentNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(557, 208, 72, -1));
        stepsToPayment.add(dateOfBirthField, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 244, 349, 24));
        stepsToPayment.add(mobileNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 275, 349, -1));
        stepsToPayment.add(altNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 311, 349, -1));
        stepsToPayment.add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 347, 349, -1));

        categoryPayment.add(oc);
        oc.setText("OC");
        oc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ocActionPerformed(evt);
            }
        });
        stepsToPayment.add(oc, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 378, 56, -1));

        categoryPayment.add(bcb);
        bcb.setText("BC_B");
        stepsToPayment.add(bcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 378, 57, -1));

        categoryPayment.add(bcc);
        bcc.setText("BC_C");
        bcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bccActionPerformed(evt);
            }
        });
        stepsToPayment.add(bcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(744, 378, -1, -1));

        categoryPayment.add(bca);
        bca.setText("BC_A");
        stepsToPayment.add(bca, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 378, 62, -1));

        categoryPayment.add(bce);
        bce.setText("BC_E");
        stepsToPayment.add(bce, new org.netbeans.lib.awtextra.AbsoluteConstraints(856, 378, -1, -1));

        categoryPayment.add(bcd);
        bcd.setText("BC_D");
        stepsToPayment.add(bcd, new org.netbeans.lib.awtextra.AbsoluteConstraints(799, 378, -1, -1));

        categoryPayment.add(sc);
        sc.setText("SC");
        stepsToPayment.add(sc, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 378, -1, -1));

        categoryPayment.add(st);
        st.setText("ST");
        stepsToPayment.add(st, new org.netbeans.lib.awtextra.AbsoluteConstraints(954, 378, -1, -1));

        ph.add(phYes);
        phYes.setText("YES");
        stepsToPayment.add(phYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 414, 56, -1));

        ph.add(phNo);
        phNo.setText("NO");
        stepsToPayment.add(phNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 414, -1, -1));

        certificate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                certificateActionPerformed(evt);
            }
        });
        stepsToPayment.add(certificate, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 451, 349, -1));

        streamAppliedFor.add(agriMedical);
        agriMedical.setText("AGRICULTURE & MEDICAL(AM)");
        agriMedical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agriMedicalActionPerformed(evt);
            }
        });
        stepsToPayment.add(agriMedical, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 517, 206, -1));

        streamAppliedFor.add(engineering);
        engineering.setText("ENGINEERING(E)");
        stepsToPayment.add(engineering, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 490, 146, -1));

        streamAppliedFor.add(bothEngAgri);
        bothEngAgri.setText("BOTH (ENGINEERING & AGRICULTURE & MEDICAL)(AM)");
        stepsToPayment.add(bothEngAgri, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 544, 349, 33));

        payFee.setText("Pay Fee");
        payFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFeeActionPerformed(evt);
            }
        });
        stepsToPayment.add(payFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 663, 288, 43));

        upi.setText("UPI");
        upi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upiActionPerformed(evt);
            }
        });
        stepsToPayment.add(upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 590, 104, -1));

        password.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        password.setText("Set Password : ");
        stepsToPayment.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 625, 156, 32));
        stepsToPayment.add(studentPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 633, 338, -1));

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        stepsToPayment.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));

        home1scroll.setViewportView(stepsToPayment);

        add(home1scroll, "card4");

        referenceNumberLabel1.setText("Enter Reference Number: ");

        upiIdField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upiIdField1ActionPerformed(evt);
            }
        });

        upiIfLabel1.setText("Enter UPI ID : ");

        submit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        payingFeeLayer1.setLayer(referenceNumberLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        payingFeeLayer1.setLayer(upiIdField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        payingFeeLayer1.setLayer(upiIfLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        payingFeeLayer1.setLayer(referenceNumberField1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        payingFeeLayer1.setLayer(submit, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout payingFeeLayer1Layout = new javax.swing.GroupLayout(payingFeeLayer1);
        payingFeeLayer1.setLayout(payingFeeLayer1Layout);
        payingFeeLayer1Layout.setHorizontalGroup(
            payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                .addGroup(payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(referenceNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(upiIdField1, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                            .addComponent(referenceNumberField1)))
                    .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(480, Short.MAX_VALUE))
            .addGroup(payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(upiIfLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(670, Short.MAX_VALUE)))
        );
        payingFeeLayer1Layout.setVerticalGroup(
            payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(upiIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(referenceNumberLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(referenceNumberField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
            .addGroup(payingFeeLayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(payingFeeLayer1Layout.createSequentialGroup()
                    .addGap(82, 82, 82)
                    .addComponent(upiIfLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(243, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout home2Layout = new javax.swing.GroupLayout(home2);
        home2.setLayout(home2Layout);
        home2Layout.setHorizontalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(payingFeeLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );
        home2Layout.setVerticalGroup(
            home2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home2Layout.createSequentialGroup()
                .addComponent(payingFeeLayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 354, Short.MAX_VALUE))
        );

        home2scroll.setViewportView(home2);

        add(home2scroll, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        Object [] values = {"continue"};
        if(finalFeeSubmitButon()){
            new FeePaymentDatabase(data);
            int val = JOptionPane.showOptionDialog(home2scroll, "Fee payment successful\nClick Proceed to fill the form","Permission",JOptionPane.YES_OPTION, JOptionPane.INFORMATION_MESSAGE,null, values,null);
            if(val ==0){
               
    CardLayout cl = (CardLayout) aw.appInterface.getLayout();
            aw.appInterface.remove(this);
            aw.appInterface.add(aw.registrationPanel);
            aw.appInterface.repaint();
            aw.appInterface.revalidate();
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please enter the details","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_submitActionPerformed

    AdminWindow awf = null;
    public void adminWindowReference(AdminWindow awf){
        this.awf= awf;
    }
    private void upiIdField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upiIdField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upiIdField1ActionPerformed

    private void stepsToPaymentMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_stepsToPaymentMouseWheelMoved

    }//GEN-LAST:event_stepsToPaymentMouseWheelMoved

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed

        Object[] options = {"Back","Proceed TO fill Form"};
     
        
         int choosenOption = JOptionPane.showOptionDialog(null,"You are in the middle of Filling Form","Warning!!",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE,null,options,null);
         if(choosenOption ==0){
            CardLayout cl = (CardLayout) aw.appInterface.getLayout();
            aw.appInterface.remove(this);
            aw.appInterface.add(aw.registrationPanel);
            aw.appInterface.repaint();
            aw.appInterface.revalidate();
         }
         else if(choosenOption==1){
             JOptionPane.getRootFrame().dispose();
         }
         
         
        
  
    }//GEN-LAST:event_backActionPerformed
    
    private void upiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upiActionPerformed

    private void payFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFeeActionPerformed
        // TODO add your handling code here:
        if(proceedButton()){
            this.removeAll();
            this.add(home2);
            this.repaint();
            this.revalidate();
        }

        else{
            JOptionPane.showMessageDialog(null, "Please Enter all details","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_payFeeActionPerformed

    private void certificateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_certificateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateActionPerformed

    private void bccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bccActionPerformed

    private void ocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ocActionPerformed

    private void boardNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boardNameFieldActionPerformed

    private void diplomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diplomaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diplomaActionPerformed

    private void mpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mpcActionPerformed

    private void bpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bpcActionPerformed

    private void agriMedicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agriMedicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agriMedicalActionPerformed
AdminWindow aw = null;
 public void passRef(AdminWindow aw){
     this.aw = aw;
 }
    
     String data[] = new String[16];
    
   
//    
//    private void setQualifyExam1(JRadioButton radioButton) {
//        if (radioButton.isSelected()) {
//            data[1] = radioButton.getText();
//        }
//    }
//     private void setQualifyExam2(JRadioButton radioButton) {
//        if (radioButton.isSelected()) {
//            data[1] = radioButton.getText();
//        }
//    }
//      private void setQualifyExam3(JRadioButton radioButton) {
//        if (radioButton.isSelected()) {
//            data[1] = radioButton.getText();
//        }
//    }
//    private void setQualifyExam4(JRadioButton radioButton) {
//        if (radioButton.isSelected()) {
//            data[1] = radioButton.getText();
//        }
//    }
     
     
     private void setQualifyExam(ButtonGroup bg ){
        Enumeration<AbstractButton> buttons = bg.getElements();
                while (buttons.hasMoreElements()) {
                    AbstractButton button = buttons.nextElement();
                    if (button.isSelected()) {
                        data[1] = button.getText();
                        break;
                    }
                }
     }
       
    public void setBoard(){
        data[2] = (String)boardNameField.getSelectedItem();
    }
    
    public void setHallticket(){
        data[3] = secondYearHallticketField.getText();
    }
     public void setStudentName(){
        data[0] = studentNameField.getText();
    }
     public void setDateOfBirth(){
        data[4] = dateOfBirthField.getText();
    }
     public void setStudentMobileNumber(){
        data[5] = mobileNumberField.getText();
    }
     public void setAltMobileNumber(){
        data[6] = altNumberField.getText();
    }
     public void setEmail(){
        data[7] = emailField.getText();
    }
    
     public void setCategory(ButtonGroup bg){
         Enumeration<AbstractButton> em = bg.getElements();
         while(em.hasMoreElements()){
             AbstractButton ab = em.nextElement();
             if(ab.isSelected()){
                 data[8] = ab.getText();
                 break;
             }
         }
         
     }
    
       
      
  private void setPh1(JRadioButton radioButton) {
        if (radioButton.isSelected()) {
            data[9] = radioButton.getText();
        }
    }
   private void setPh2(JRadioButton radioButton) {
        if (radioButton.isSelected()) {
            data[9] = radioButton.getText();
        }
    }
  
   public void setCertificate(){
      data[10] = certificate.getText();
    }
   
    private void setStream1(JRadioButton radioButton) {
        if (radioButton.isSelected()) {
            data[11] = radioButton.getText();
        }
    }
     private void setStream2(JRadioButton radioButton) {
        if (radioButton.isSelected()) {
            data[11] = radioButton.getText();
        }
    }
      private void setStream3(JRadioButton radioButton) {
        if (radioButton.isSelected()) {
            data[11] = radioButton.getText();
        }
    }
        public void setPaymentType(){
           data[12] = upi.getText();
    }
        public void setPassword(){
            char[] ch =  studentPasswordField.getPassword();
            String pass = new String(ch);
             data[13] = pass;
        }
        public void setUpiId(){
            data[14] = upiIdField1.getText();
        }
        public void setReferenceNumber(){
            data[15] = referenceNumberField1.getText();
        }
        
        public boolean finalFeeSubmitButon(){
            setUpiId();
            setReferenceNumber();
            if(data[14]==null || data[15] ==null){
             
                return false;
            }
            return true;
            
        }
   
        public void setDataOfForm(){
             setQualifyExam(qualifyExam);
            setBoard();
            setHallticket();
            
            setStudentName();
            setDateOfBirth();
            setStudentMobileNumber();
            setAltMobileNumber();
            setEmail();
            setCategory(categoryPayment);
            setPh1(phYes);
            setPh2(phNo);
            setCertificate();
            setStream1(engineering);
            setStream2(bothEngAgri);
            setStream3(agriMedical);
            setPassword();
           setPaymentType();
        }
        
        public boolean proceedButton(){
           setDataOfForm();
          
            boolean temp = true;
            for(int i =0;i<13;i++){
                if(data[i] ==null &&(data[10]==null || data[10]!=null)){
                    temp = false;
                }
            }
            return temp;
        }
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agriMedical;
    private javax.swing.JLabel altNumber;
    private javax.swing.JTextField altNumberField;
    private javax.swing.JButton back;
    private javax.swing.JRadioButton bca;
    private javax.swing.JRadioButton bcb;
    private javax.swing.JRadioButton bcc;
    private javax.swing.JRadioButton bcd;
    private javax.swing.JRadioButton bce;
    private javax.swing.JLabel boardName;
    private javax.swing.JComboBox<String> boardNameField;
    private javax.swing.JRadioButton bothEngAgri;
    private javax.swing.JRadioButton bpc;
    private javax.swing.JLabel category;
    private javax.swing.ButtonGroup categoryPayment;
    private javax.swing.JTextField certificate;
    private javax.swing.JLabel certificateNumber;
    private javax.swing.JLabel dateOfBirth;
    private javax.swing.JTextField dateOfBirthField;
    private javax.swing.JRadioButton diploma;
    private javax.swing.JLabel email;
    private javax.swing.JTextField emailField;
    private javax.swing.JRadioButton engineering;
    private javax.swing.JLabel heading;
    private javax.swing.JScrollPane home1scroll;
    private javax.swing.JPanel home2;
    private javax.swing.JScrollPane home2scroll;
    private javax.swing.JLabel intermediateBranch;
    private javax.swing.JRadioButton mbpc;
    private javax.swing.JTextField mobileNumberField;
    private javax.swing.JRadioButton mpc;
    private javax.swing.JRadioButton oc;
    private javax.swing.JLabel password;
    private javax.swing.JButton payFee;
    private javax.swing.JLayeredPane payingFeeLayer1;
    private javax.swing.JLabel paymentMethod;
    private javax.swing.ButtonGroup ph;
    private javax.swing.JRadioButton phNo;
    private javax.swing.JRadioButton phYes;
    private javax.swing.JLabel physicallyHandicapped;
    private javax.swing.ButtonGroup qualifyExam;
    private javax.swing.JTextField referenceNumberField1;
    private javax.swing.JLabel referenceNumberLabel1;
    private javax.swing.JRadioButton sc;
    private javax.swing.JLabel secondYearHallTicket;
    private javax.swing.JTextField secondYearHallticketField;
    private javax.swing.JRadioButton st;
    private javax.swing.JLayeredPane stepsToPayment;
    private javax.swing.JLabel streamApplied;
    private javax.swing.ButtonGroup streamAppliedFor;
    private javax.swing.JLabel studentName;
    private javax.swing.JTextField studentNameField;
    private javax.swing.JLabel studentNumber;
    private javax.swing.JPasswordField studentPasswordField;
    private javax.swing.JButton submit;
    private javax.swing.JRadioButton upi;
    private javax.swing.JTextField upiIdField1;
    private javax.swing.JLabel upiIfLabel1;
    // End of variables declaration//GEN-END:variables

    
}
